#ifndef YOLO_CONFIG_H_
#define YOLO_CONFIG_H_

namespace yolo {

extern int BASESPEED;

extern int TICKS_FORWARD_BEFORE_CROSSING_GUARD;
extern int TICKS_AFTER_CROSSING;

extern int TICKS_TURN;
extern int TICKS_TURN_BEFORE_CROSSING_GUARD;

extern int TICKS_CHECKSIGN_MOVE;
extern int TICKS_CHECKSIGN_TURNSERVOS;
extern int TICKS_CHECKSIGN_CHECKSIGN;

extern int CAMERA_CHECKSIGN_FORWARD_PAN;
extern int CAMERA_CHECKSIGN_FORWARD_TILT;

extern int CAMERA_CHECKSIGN_LEFT_PAN;
extern int CAMERA_CHECKSIGN_LEFT_TILT;

extern int CAMERA_CHECKSIGN_RIGHT_PAN;
extern int CAMERA_CHECKSIGN_RIGHT_TILT;

int loadConfig();

} // namespace yolo

#endif // YOLO_CONFIG_H_
